# R Notes

----

1) R Basics
    1.1) Arithmetics: +,-, *,^, %%
    1.2) Data types
    1.3) Vectors: names(), sum(), selection vector
    1.4) Matrices: matrix(), colnames(), rownames(), dimnames(), cbind(), rbind(), matrix arithmetics
    1.5) Factors: factor(), levels(), summary(), selection, comparison
    1.6) DataFrames: head(), tail(), str(), summary(), data.frame(), selection, subset(), order(), 
    1.7) Lists: create list, slice list, concat list

2) R Intermediate
    2.1) Relational Operators: ==, !=, >, <
    
    

## 1) R Basics

### 1.1) Arithmetics


For simple arithmetics use:

+ , - , * , / , 
Exponetiation : ^
Module : %%

For matrix arithmetics use %*% or %/ % , else all elements are calculated and the arithmetic is not the usual matrix one.

---

### 1.2) Basic Data Types

Numerics   : 4.5

Integers   : 4

Boolean    : TRUE, FALSE, T, F

Characters : 'this is a text', 'abc'

Vectors, Matrices, Factors and Lists are made using the basic data types.



To find the type of a variable use: **class(variable_name)**



In [95]:
var <- 4.1

In [96]:
class(var)

[1] "numeric"

---

### 1.3) Vectors

To create a vector 

In [97]:
myvec <- c(1,3,5.5); myvec

[1] 1.0 3.0 5.5

Naming the vector by :

In [98]:
names(myvec) <- c('a','b','c'); myvec

a   b   c 
1.0 3.0 5.5

Summing the elements of a vector:

In [99]:
sum(myvec)

[1] 9.5

Select a vector index:

In [100]:
myvec[2]        # counting starts from 1 not 0!

b 
3

In [101]:
myvec[c(1,2)]   # multiple select

a b 
1 3

In [102]:
myvec[1:2]      # slicing

a b 
1 3

In [103]:
myvec[c('a','b')] # by name

a b 
1 3

---
Selection by vector comparison:

In [104]:
poker_vector <- c(140, -50, 20, -120, 240);
selection <- poker_vector > 0;
selection

[1]  TRUE FALSE  TRUE FALSE  TRUE

In [105]:
winnings_vector <- poker_vector[selection]; winnings_vector

[1] 140  20 240

---


### 1.4) Matrices

Using the matrix function we can make a 2D matrix:


In [106]:
matrix(1:9, byrow = TRUE, nrow =3) # byrow : fill by rows , nrow = # rows

[,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

---
**create a matrix using vectors:**


In [107]:
new_hope <- c(460.998, 314.4);
empire_strikes <- c(290.475, 247.900);
return_jedi <- c(309.306, 165.8);

star_wars_matrix = matrix(c(new_hope,empire_strikes,return_jedi), nrow=3,
                          byrow=TRUE);
star_wars_matrix

[,1]  [,2]
[1,] 460.998 314.4
[2,] 290.475 247.9
[3,] 309.306 165.8

---

**Name your columns, rows**

In [108]:
colnames(star_wars_matrix) <- c("US", "non-US");
rownames(star_wars_matrix) <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi");
star_wars_matrix

US non-US
A New Hope              460.998  314.4
The Empire Strikes Back 290.475  247.9
Return of the Jedi      309.306  165.8

----
**Summing rows and cols:**


In [109]:
colSums(star_wars_matrix)

US   non-US 
1060.779  728.100

In [110]:
rowSums(star_wars_matrix)

A New Hope The Empire Strikes Back      Return of the Jedi 
                775.398                 538.375                 475.106

In [111]:
box_office_all <- c(461, 314.4, 290.5, 247.9, 309.3, 165.8);
movie_names <- c("A New Hope","The Empire Strikes Back","Return of the Jedi");
col_titles <- c("US","non-US")

#### NAME USING VECTOR NAMES
star_wars_matrix <- matrix(box_office_all, nrow = 3, byrow = TRUE, 
                           dimnames = list(movie_names, col_titles));

star_wars_matrix


US non-US
A New Hope              461.0  314.4
The Empire Strikes Back 290.5  247.9
Return of the Jedi      309.3  165.8

---

**Adding columns and rows** : cbind(), rbind()

In [112]:
worldwide_vector <- rowSums(star_wars_matrix);
all_wars_matrix <- cbind(star_wars_matrix, worldwide_vector)
all_wars_matrix

US non-US worldwide_vector
A New Hope              461.0  314.4            775.4
The Empire Strikes Back 290.5  247.9            538.4
Return of the Jedi      309.3  165.8            475.1

In [113]:
box_office_2 <- c(474, 552, 310, 338, 380, 468);
movie_names_2 <- c("The Phantom Menace","Attack of the Clones","Revenge of the Sith");
col_titles_2 <- c("US","non-US")
star_wars_matrix_2 <- matrix(box_office_2, nrow = 3, byrow = TRUE, 
                           dimnames = list(movie_names_2, col_titles_2));


star_wars_all <- rbind(star_wars_matrix,star_wars_matrix_2);
star_wars_all

US non-US
A New Hope              461.0  314.4
The Empire Strikes Back 290.5  247.9
Return of the Jedi      309.3  165.8
The Phantom Menace      474.0  552.0
Attack of the Clones    310.0  338.0
Revenge of the Sith     380.0  468.0

----

** Selecting elements of matrix **



In [114]:
star_wars_all[1,2] #1st row, 2nd column

[1] 314.4

In [115]:
star_wars_all[ ,2] # ALL rows from 2nd column

A New Hope The Empire Strikes Back      Return of the Jedi 
                  314.4                   247.9                   165.8 
     The Phantom Menace    Attack of the Clones     Revenge of the Sith 
                  552.0                   338.0                   468.0

In [116]:
star_wars_all[1, ] # 1st row, all columns

US non-US 
 461.0  314.4

In [117]:
star_wars_all[1:2,] #slicing

US non-US
A New Hope              461.0  314.4
The Empire Strikes Back 290.5  247.9

In [118]:
mean(star_wars_all[1:2,])

[1] 328.45

---

**Arithmetics with matrices**

In [119]:
star_wars_all *2 # multiply all elements by 2

US non-US
A New Hope              922.0  628.8
The Empire Strikes Back 581.0  495.8
Return of the Jedi      618.6  331.6
The Phantom Menace      948.0 1104.0
Attack of the Clones    620.0  676.0
Revenge of the Sith     760.0  936.0



---


### 1.4 Factors

Factors are used for categorical variables, i.e. 'Gender'

Having a vector with elements from two categories you can make a factor variable by calling the `factor()` function:



In [120]:
gender_vector <- c("Male", "Female", "Female", "Male", "Male");
factor_gender_vector <- factor(gender_vector);
factor_gender_vector

[1] Male   Female Female Male   Male  
Levels: Female Male

---

There are two types of categorical variables **nominal** and **ordinal**.
You can use arguments in the factor function to define the levels of an ordinal variable.

For example:



In [121]:
animals_vector <- c("Elephant", "Giraffe", "Donkey", "Horse")
temperature_vector <- c("High", "Low", "High","Low", "Medium")

factor_animals_vector <- factor(animals_vector)
factor_animals_vector
factor_temperature_vector <- factor(temperature_vector, order = TRUE, levels = c("Low", "Medium", "High"))
factor_temperature_vector 

# in R terminal this shows also the levels :
# for the nominal it states: Levels: Donkey Elephant Giraffe Horse
# while for the ordinal : Levels: Low < Medium < High

[1] Elephant Giraffe  Donkey   Horse   
Levels: Donkey Elephant Giraffe Horse

[1] High   Low    High   Low    Medium
Levels: Low < Medium < High

---

**You can change the names of the levels by `levels()` function:**


In [122]:
survey_vector <- c("M", "F", "F", "M", "M")
factor_survey_vector <- factor(survey_vector)
factor_survey_vector

[1] M F F M M
Levels: F M

but I want 'Male' and 'Female' !

In [123]:
levels(factor_survey_vector) <- c('Female', 'Male')

In [124]:
factor_survey_vector

[1] Male   Female Female Male   Male  
Levels: Female Male

---
**Summary** of factors

In [125]:
summary(survey_vector)

   Length     Class      Mode 
        5 character character 

In [126]:
summary(factor_survey_vector)

Female   Male 
     2      3

---

** Selection **


In [127]:
factor_survey_vector[1]

[1] Male
Levels: Female Male

In [128]:
factor_survey_vector[2]

[1] Female
Levels: Female Male

---

** Comparison of factors **

Comparison does not work for nominal factors,
but works fine for ordinal!!

In [129]:
factor_survey_vector[1]>factor_survey_vector[2] ## NA! Doesn't work for 
                                                ## nominal factors!

Warning message:
In Ops.factor(factor_survey_vector[1], factor_survey_vector[2]): ‘>’ not meaningful for factors

[1] NA

In [130]:
speed_vector <- c("Fast", "Slow", "Slow", "Fast", "Ultra-fast")
factor_speed_vector <- factor(speed_vector, ordered = TRUE, 
                              levels = c("Slow", "Fast", "Ultra-fast"))

compare_them <- factor_speed_vector[2]>factor_speed_vector[5]

# Is data analyst 2 faster than data analyst 5?
compare_them

[1] FALSE

----

### 1.6) DataFrame

Contrary to matrices, dataframes can hold data of various types

In [131]:
mtcars;  # dataframe included in R 

mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3
Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4
Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2
AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2
Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4
Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2
Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4
Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6
Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8
Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2

---

**Quick look at dataframe**
head(), tail(), str() [structure]


In [132]:
head(mtcars,2)

mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4      21   6  160 110  3.9 2.620 16.46  0  1    4    4
Mazda RX4 Wag  21   6  160 110  3.9 2.875 17.02  0  1    4    4

In [133]:
tail(mtcars,4)

mpg cyl disp  hp drat   wt qsec vs am gear carb
Ford Pantera L 15.8   8  351 264 4.22 3.17 14.5  0  1    5    4
Ferrari Dino   19.7   6  145 175 3.62 2.77 15.5  0  1    5    6
Maserati Bora  15.0   8  301 335 3.54 3.57 14.6  0  1    5    8
Volvo 142E     21.4   4  121 109 4.11 2.78 18.6  1  1    4    2

In [134]:
str(mtcars) # means structure

'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...


In [135]:
summary(mtcars)  # returns summary statistics

      mpg             cyl             disp             hp       
 Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0  
 1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5  
 Median :19.20   Median :6.000   Median :196.3   Median :123.0  
 Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7  
 3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0  
 Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0  
      drat             wt             qsec             vs        
 Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000  
 1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000  
 Median :3.695   Median :3.325   Median :17.71   Median :0.0000  
 Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375  
 3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000  
 Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000  
       am              gear            carb      
 Min.   :0.0000   Min.   :3.000  

---

** Creating a data.frame()**

You can create a dataframe using simple vectors by calling the `data.frame()` function


In [136]:
planets <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune");
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883); 
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67);
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE);

# Create the data frame:
planets_df  <- data.frame(planets, type, diameter, rotation, rings)
planets_df  # indexes the rows and names the columns by the name of vector

planets               type diameter rotation rings
1 Mercury Terrestrial planet    0.382    58.64 FALSE
2   Venus Terrestrial planet    0.949  -243.02 FALSE
3   Earth Terrestrial planet    1.000     1.00 FALSE
4    Mars Terrestrial planet    0.532     1.03 FALSE
5 Jupiter          Gas giant   11.209     0.41  TRUE
6  Saturn          Gas giant    9.449     0.43  TRUE
7  Uranus          Gas giant    4.007    -0.72  TRUE
8 Neptune          Gas giant    3.883     0.67  TRUE

---
**Slicing a data frame**

As with matrices you can use [1,2], [1, ], [1:3, ] etc

** OR USE THE NAME OF THE COLUMN!!! **


In [137]:
planets_df[1:3,1]

[1] Mercury Venus   Earth  
Levels: Earth Jupiter Mars Mercury Neptune Saturn Uranus Venus

In [138]:
planets_df[3:8, "diameter"]

[1]  1.000  0.532 11.209  9.449  4.007  3.883

In [139]:
planets_df$diameter # this returns a vector with the elements of the column
## similar to planets_df[ ,"diameter"]

[1]  0.382  0.949  1.000  0.532 11.209  9.449  4.007  3.883

---

**Selection of df entries using selector vector**

In [140]:
selection_rings <- planets_df$rings

In [141]:
planets_with_rings <- planets_df[selection_rings, ] # all columns, 
                                                    #rows with True

In [142]:
planets_with_rings

planets      type diameter rotation rings
5 Jupiter Gas giant   11.209     0.41  TRUE
6  Saturn Gas giant    9.449     0.43  TRUE
7  Uranus Gas giant    4.007    -0.72  TRUE
8 Neptune Gas giant    3.883     0.67  TRUE


** Subset()**

Use the subset function to select entries from a df


In [143]:
planets_with_rings_2 <- subset(planets_df, subset = rings == TRUE);
planets_with_rings_2

planets      type diameter rotation rings
5 Jupiter Gas giant   11.209     0.41  TRUE
6  Saturn Gas giant    9.449     0.43  TRUE
7  Uranus Gas giant    4.007    -0.72  TRUE
8 Neptune Gas giant    3.883     0.67  TRUE

----

** Order ** 

the order() function returns the hierarchical order in a vector:

In [144]:
a<- c(100, 150, 101)

In [145]:
order(a)

[1] 1 3 2



This can be used in data frames. For example order the planet df with the largest planet in the top.

To do this use the order function with the decreasing = TRUE argument to make a vector and then pass it in the df :


In [146]:
positions <- order(planets_df$diameter, decreasing=TRUE)

In [147]:
largest_first_df <- planets_df[positions, ]

In [148]:
largest_first_df

planets               type diameter rotation rings
5 Jupiter          Gas giant   11.209     0.41  TRUE
6  Saturn          Gas giant    9.449     0.43  TRUE
7  Uranus          Gas giant    4.007    -0.72  TRUE
8 Neptune          Gas giant    3.883     0.67  TRUE
3   Earth Terrestrial planet    1.000     1.00 FALSE
2   Venus Terrestrial planet    0.949  -243.02 FALSE
4    Mars Terrestrial planet    0.532     1.03 FALSE
1 Mercury Terrestrial planet    0.382    58.64 FALSE

---
### 1.7) Lists

Lists hold together objects from different data types, sizes and flavors under one common name.

To make a list just use the `list()` function with arguments the things you want the list to hold

In [149]:
vec <- 1:10;
mat <- matrix(1:9, byrow=TRUE, ncol=3)
mdf <- mtcars[1:10,]

In [151]:
my_list <- list(vec, mat, mdf)
my_list

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

[[3]]
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

Update the `names(my_list)` to name the object your list holds:

In [155]:
names(my_list) <- c("vector", "matrix", "dataframe")

In [156]:
my_list

ERROR: Error in vapply(seq_along(mapped), function(i) {: values must be length 1,
 but FUN(X[[3]]) result is length 0


$vector
 [1]  1  2  3  4  5  6  7  8  9 10

$matrix
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

$dataframe
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

---
** Select elements from list **

To select from the list use the double bracket [[ ]]

In [159]:
my_list[[1]] # returns the object 1 (ie the vector)

[1]  1  2  3  4  5  6  7  8  9 10

In [160]:
my_list[[2]]

[,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

In [164]:
my_list[[1]][2] #from the list the 1st object (vec), 
                # from that the 2nd element

[1] 2

----

**Append to list**

To append an info in the list use the c() function.
To also name the new item when concatinating use the syntax :

` c(list, name=new_var)`


In [166]:
year <- 1980
my_list_2 <- c(my_list, myyear=year)
my_list_2


ERROR: Error in vapply(seq_along(mapped), function(i) {: values must be length 1,
 but FUN(X[[3]]) result is length 0


$vector
 [1]  1  2  3  4  5  6  7  8  9 10

$matrix
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

$dataframe
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

$myyear
[1] 1980

---
---

## 2) Intermediate R

### 2.1) Relational Operators

These operators are ==, !=, <, >,  and can be used to return TRUE or FALSE.

Some interesting cases:



In [167]:
3>5

[1] FALSE

In [168]:
FALSE == TRUE

[1] FALSE

In [169]:
FALSE < TRUE  # TRUE = 1, FALSE = 0

[1] TRUE

In [171]:
"Hello" > "Goodbye" # alphabetical order (G < H < I ...)

[1] TRUE

---
For vectors:


In [172]:
linkedin <- c (10,20,30,40,60)

In [173]:
linkedin > 30

[1] FALSE FALSE FALSE  TRUE  TRUE

In [176]:
facebook <- c(10,50,20,56) # check the warning

In [177]:
linkedin<facebook

Warning message:
In linkedin < facebook: longer object length is not a multiple of shorter object length

[1] FALSE  TRUE FALSE  TRUE FALSE